### ISSUE TITLE
Delete function

### ISSUE THREAD

**Issue by RunGT** [fac20/week6-ELMP#34]
Hi party people, lovely site! Really impressive stuff.

I found a small issue with trying to delete something. A logged in the user is allowed to input any name when entering a cookie post. If the name inputted doesn't match the logged in username I am unable to delete.

A solution could be to auto fill the name value with the logged in user name?

**Comment by CampbellDocherty** [comment]
If you have the username in the cookie then you can just take it from there in the handlers and only have the text content form field so the logged in user will always post under their username - - if I've understood the issue correctly

**Comment by amberrignell** [comment]
Done ! Thanks for the tips :))
