### ISSUE TITLE
Console logs are left in some functions

### ISSUE THREAD

**Issue by RihardsJ** [fac20/week6-ELMP#48]
function loginHandler(request, response) {
	let body = "";
	request.on("data", (chunk) => (body += chunk));
	request.on("end", () => {
		const searchParams = new URLSearchParams(body); // turns form post string in to an object
		const user = Object.fromEntries(searchParams); //user {username: xxx, password: xxx}
		console.log("user l60", user)
		db.query("SELECT * from USERS WHERE username = ($1)", [user.username])
		.then((data) => {
			data = data.rows[0]; //{id:dgsd , username: rshuigs, password: dfsg}
			console.log("data",data)
			console.log(user.password, data.password)
			console.log(typeof user.password, typeof data.password)
			return bcrypt.compare(user.password, data.password)
		})

**Comment by amberrignell** [comment]
removed :) Nice catch
